# Generated by Django 2.0 on 2018-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.IntegerField(default=0)),
                ('choice2', models.IntegerField(default=0)),
                ('name', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_names', models.CharField(default=' ', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_names', models.CharField(default=' ', max_length=1000)),
            ],
        ),
    ]
